import { getClient } from "@/lib/db"
import { notFound } from "next/navigation"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { ArrowLeft, ArrowRight, MessageSquare, Target, Zap, Clock, Activity, AlertCircle, Bot, Brain, LineChart, LayoutDashboard, Briefcase, TrendingUp, Cpu, Calendar, ShieldAlert, FileText } from "lucide-react"
import { Navbar } from "@/components/layout/Navbar"

function AgentBadge({ name, icon: Icon, colorClass }: { name: string, icon: any, colorClass: string }) {
  return (
    <div className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-muted/50 border border-muted text-xs font-medium ${colorClass}`}>
      <Icon className="w-3.5 h-3.5" />
      Generated by {name}
    </div>
  )
}

function SmallAgentBadge({ name, icon: Icon, colorClass }: { name: string, icon: any, colorClass: string }) {
  return (
    <div className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-md bg-muted/30 border border-muted/50 text-[10px] font-medium ${colorClass}`}>
      <Icon className="w-3 h-3" />
      {name}
    </div>
  )
}

export default async function ProspectDetailPage({ params }: { params: Promise<{ clientId: string }> }) {
  const resolvedParams = await params;
  const client = await getClient(resolvedParams.clientId)
  
  if (!client) {
    notFound()
  }

  const latestPulsePlan = client.pulsePlans.length > 0 ? client.pulsePlans[client.pulsePlans.length - 1] : null;

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      <div className="container mx-auto py-10 space-y-8 max-w-6xl flex-1">
        {/* Back Link */}
        <Link href="/templates" className="inline-flex items-center text-sm font-medium text-muted-foreground hover:text-foreground mb-4">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Templates
        </Link>
        
      {/* Header & Profile */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 pb-6 border-b border-border/50">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <h1 className="text-4xl font-bold tracking-tight">{client.companyName}</h1>
            <span className="px-3 py-1 bg-primary/10 text-primary rounded-full text-sm font-semibold capitalize">
              {client.stage.replace('_', ' ')}
            </span>
          </div>
          <p className="text-muted-foreground max-w-2xl">{client.customerContext}</p>
          <div className="flex items-center gap-4 mt-4 text-sm text-muted-foreground">
            <span className="flex items-center gap-1"><Clock className="w-4 h-4" /> Updated {new Date(client.updatedAt).toLocaleDateString()}</span>
            <span className="flex items-center gap-1"><Activity className="w-4 h-4" /> Version {client.evolutionHistory.length + 1}</span>
          </div>
        </div>
        
        {/* Action Hub - Continue Prospect */}
        <div className="flex flex-wrap gap-3">
          <Link href={`/pulse-plan/${client.id}`}>
            <Button className="gap-2 shadow-md"><Target className="w-4 h-4" /> Generate Pulse Plan</Button>
          </Link>
          <Link href={`/debrief/${client.id}`}>
            <Button variant="secondary" className="gap-2 shadow-sm"><MessageSquare className="w-4 h-4" /> Log Debrief</Button>
          </Link>
          <Link href={`/improvement/${client.id}`}>
            <Button variant="outline" className="gap-2 shadow-sm"><Zap className="w-4 h-4" /> Evolve Pitch</Button>
          </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column (Main Content) */}
        <div className="lg:col-span-2 space-y-8">
          
          {/* Active Pitch */}
          <section>
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-2xl font-semibold flex items-center gap-2"><Zap className="w-5 h-5 text-amber-500"/> Current Active Pitch (v{client.evolutionHistory.length + 1})</h2>
              <AgentBadge name={client.evolutionHistory.length > 0 ? "Pitch Evolution Agent" : "Pitch Generation Agent"} icon={SparklesIcon} colorClass="text-amber-600 dark:text-amber-400" />
            </div>
            <Card className="shadow-md border-primary/20">
              <CardContent className="p-6 space-y-6">
                <div>
                  <h3 className="font-semibold text-primary mb-2 text-sm uppercase tracking-wider">Cold Call Opener</h3>
                  <p className="text-sm bg-muted/40 p-4 rounded-lg border border-muted-foreground/10">{client.evolvingPitch.coldCallOpener}</p>
                </div>
                <div>
                  <h3 className="font-semibold text-primary mb-2 text-sm uppercase tracking-wider">Core Narrative</h3>
                  <p className="text-sm bg-muted/40 p-4 rounded-lg border border-muted-foreground/10">{client.evolvingPitch.coreNarrative}</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="font-semibold text-primary mb-2 text-sm uppercase tracking-wider">Discovery Questions</h3>
                    <ul className="list-disc pl-5 text-sm space-y-2 text-muted-foreground">
                      {client.evolvingPitch.discoveryQuestions.map((q, i) => <li key={i}><span className="text-foreground">{q}</span></li>)}
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-semibold text-primary mb-2 text-sm uppercase tracking-wider">Value Positioning</h3>
                    <ul className="list-disc pl-5 text-sm space-y-2 text-muted-foreground">
                      {client.evolvingPitch.valuePositioning.map((v, i) => <li key={i}><span className="text-foreground">{v}</span></li>)}
                    </ul>
                  </div>
                </div>
                <div>
                  <h3 className="font-semibold text-primary mb-2 text-sm uppercase tracking-wider">Common Objections</h3>
                  <div className="flex flex-wrap gap-2">
                    {client.evolvingPitch.commonObjections.map((o, i) => (
                      <span key={i} className="text-xs bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300 px-3 py-1.5 rounded-full font-medium border border-red-200 dark:border-red-800/50">{o}</span>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Pitch Evolution Timeline */}
          {client.evolutionHistory.length > 0 && (
            <section>
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2"><Clock className="w-5 h-5"/> Agent Evolution Timeline</h2>
              <div className="space-y-6">
                {client.evolutionHistory.slice().reverse().map((evo, index) => (
                  <Card key={evo.id} className="relative overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                    <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-gradient-to-b from-amber-500 to-amber-500/40"></div>
                    <CardHeader className="pb-3 bg-muted/10 border-b">
                      <div className="flex justify-between items-center mb-2">
                        <SmallAgentBadge name="Pitch Evolution Agent" icon={SparklesIcon} colorClass="text-amber-600 dark:text-amber-400" />
                        <span className="text-xs font-medium text-muted-foreground bg-muted px-2 py-1 rounded-md">{new Date(evo.timestamp).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <CardTitle className="text-lg flex items-center gap-2">
                          <span className="bg-primary text-primary-foreground w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold">v{evo.version}</span>
                          Update
                        </CardTitle>
                      </div>
                      <p className="text-sm font-semibold text-amber-600 dark:text-amber-400 mt-2 flex items-center gap-1.5">
                        <Cpu className="w-3.5 h-3.5"/> Trigger: {evo.triggerEvent}
                      </p>
                    </CardHeader>
                    <CardContent className="pt-4">
                      {evo.aiSummary && (
                        <div className="text-sm bg-blue-50/50 dark:bg-blue-900/10 p-4 rounded-lg mb-5 border border-blue-100 dark:border-blue-800/30">
                          <p><strong className="text-blue-800 dark:text-blue-300">Why Changed:</strong> <span className="text-muted-foreground">{evo.aiSummary.whyChanged}</span></p>
                          <p className="mt-2"><strong className="text-blue-800 dark:text-blue-300">What Improved:</strong> <span className="text-muted-foreground">{evo.aiSummary.whatImproved}</span></p>
                        </div>
                      )}
                      <div className="space-y-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">Applied Changes</h4>
                        {evo.appliedChanges.map((change, i) => (
                          <div key={i} className="flex items-start gap-3 text-sm bg-muted/30 p-2 rounded">
                            <ArrowRight className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                            <span>{change}</span>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </section>
          )}

          {/* Intelligence Flow */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2"><Cpu className="w-5 h-5"/> Agent Intelligence Flow</h2>
            <Card className="shadow-sm border-zinc-200 dark:border-zinc-800">
              <CardContent className="p-6">
                <div className="relative pl-6 space-y-8 before:absolute before:inset-0 before:ml-[11px] before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-border before:to-transparent">
                  
                  <FlowStep 
                    agent="Learning Agent" 
                    icon={Brain} 
                    color="text-purple-500" 
                    status="Pattern Extracted" 
                    consumed="Debrief Data, Objection History" 
                    output="Learning Insights" 
                  />
                  <FlowStep 
                    agent="Strategy Agent" 
                    icon={Target} 
                    color="text-rose-500" 
                    status="Strategy Recommended" 
                    consumed="Learning Insights, Stage Data" 
                    output="Deal Strategy" 
                  />
                  <FlowStep 
                    agent="Forecast Agent" 
                    icon={TrendingUp} 
                    color="text-emerald-500" 
                    status="Forecast Updated" 
                    consumed="Deal Strategy, Confidence Trend" 
                    output="Pipeline Health Score" 
                  />
                  <FlowStep 
                    agent="Revenue Intelligence Agent" 
                    icon={ShieldAlert} 
                    color="text-red-500" 
                    status="Executive Alert Generated" 
                    consumed="Forecast Updates" 
                    output="Revenue Risk/Growth Opportunities" 
                  />

                </div>
              </CardContent>
            </Card>
          </section>

        </div>

        {/* Right Column (Sidebar) */}
        <div className="space-y-6">

          {/* Learning Agent Insights */}
          <Card className="shadow-sm border-purple-500/30 bg-purple-500/5">
            <CardHeader className="pb-3 border-b border-purple-500/10">
              <div className="flex justify-between items-center">
                <CardTitle className="text-base flex items-center gap-2"><Brain className="w-4 h-4 text-purple-500"/> Learning Agent Insights</CardTitle>
                <SmallAgentBadge name="Learning Agent" icon={Brain} colorClass="text-purple-600 dark:text-purple-400 bg-purple-100 dark:bg-purple-900/30" />
              </div>
            </CardHeader>
            <CardContent className="pt-4 space-y-4">
              <div>
                <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground block mb-1">Top Objection Learned</span>
                <p className="text-sm font-medium text-foreground">
                  {client.objectionHistory.length > 0 ? client.objectionHistory[client.objectionHistory.length - 1] : "Insufficient data"}
                </p>
              </div>
              <div>
                <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground block mb-1">Confidence Trend</span>
                <p className="text-sm font-medium text-foreground">
                  {client.confidenceTrend.length > 1 
                    ? (client.confidenceTrend[client.confidenceTrend.length - 1] > client.confidenceTrend[client.confidenceTrend.length - 2] ? "↑ Improving" : "↓ Declining") 
                    : "Stable"}
                </p>
              </div>
            </CardContent>
          </Card>
          
          {/* Latest Pulse Plan */}
          {latestPulsePlan && (
            <Card className="shadow-sm">
              <CardHeader className="pb-3 border-b bg-muted/5">
                <div className="flex justify-between items-center">
                  <CardTitle className="text-base flex items-center gap-2"><Calendar className="w-4 h-4 text-indigo-500"/> Latest Pulse Plan</CardTitle>
                  <SmallAgentBadge name="Pulse Planning Agent" icon={Calendar} colorClass="text-indigo-600 dark:text-indigo-400" />
                </div>
              </CardHeader>
              <CardContent className="space-y-5 pt-4">
                <div>
                  <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground block mb-1">Objective</span>
                  <p className="text-sm font-medium">{latestPulsePlan.callObjective}</p>
                </div>
                <div>
                  <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground block mb-1">Predicted Objection</span>
                  <p className="text-sm italic border-l-2 border-amber-500 pl-3 py-1 my-1 bg-amber-50/50 dark:bg-amber-900/10 rounded-r-md">{latestPulsePlan.predictedObjection}</p>
                </div>
                <Link href={`/pulse-plan/${client.id}`}>
                  <Button variant="ghost" className="w-full h-auto text-xs py-2 mt-2 bg-muted/50 hover:bg-muted">View Full Plan &rarr;</Button>
                </Link>
              </CardContent>
            </Card>
          )}

          {/* Recommended Next Action */}
          <Card className="border-primary/40 bg-primary/5 shadow-md overflow-hidden relative">
            <div className="absolute top-0 right-0 w-16 h-16 bg-primary/10 rounded-bl-full -mr-8 -mt-8"></div>
            <CardHeader className="pb-2">
              <div className="flex justify-between items-center mb-1">
                 <CardTitle className="text-base text-primary font-bold">Recommended Action</CardTitle>
                 <SmallAgentBadge name="Strategy Agent" icon={Target} colorClass="text-rose-600 dark:text-rose-400" />
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-sm font-medium mb-5 text-muted-foreground leading-relaxed">
                {client.stage === 'awareness' && "Schedule a discovery call to deeply understand their challenges. A Pulse Plan can help you prepare."}
                {client.stage === 'interest' && "Generate a customized Pulse Plan before your next interaction to ensure you hit the right notes."}
                {client.stage === 'desire' && "Log a debrief to track objections and evolve the pitch for closing."}
                {client.stage === 'action' && "Prepare a formal proposal focusing on ROI and business value."}
                {(client.stage === 'closed_won' || client.stage === 'closed_lost') && "Review the debrief history to extract team learning patterns for future deals."}
              </p>
              <Link href={`/pulse-plan/${client.id}`} className="w-full block">
                <Button className="w-full font-semibold shadow-sm">Take Action</Button>
              </Link>
            </CardContent>
          </Card>

          {/* Workspace Connections */}
          <Card className="shadow-sm border-zinc-200 dark:border-zinc-800">
            <CardHeader className="pb-3 border-b bg-muted/5">
              <CardTitle className="text-base flex items-center gap-2"><LayoutDashboard className="w-4 h-4 text-primary"/> Workspace Connections</CardTitle>
            </CardHeader>
            <CardContent className="pt-4 space-y-4">
              <p className="text-xs text-muted-foreground italic mb-2">This prospect intelligence currently influences forecasting, coaching, and revenue intelligence.</p>
              
              <div className="space-y-2">
                <Link href="/rep" className="flex items-center justify-between p-2 rounded-md hover:bg-muted border border-transparent hover:border-border transition-all">
                  <div className="flex items-center gap-2">
                    <Briefcase className="w-4 h-4 text-blue-500" />
                    <span className="text-sm font-medium">Sales Workspace</span>
                  </div>
                  <ArrowRight className="w-3 h-3 text-muted-foreground" />
                </Link>
                <Link href="/manager" className="flex items-center justify-between p-2 rounded-md hover:bg-muted border border-transparent hover:border-border transition-all">
                  <div className="flex items-center gap-2">
                    <LayoutDashboard className="w-4 h-4 text-emerald-500" />
                    <span className="text-sm font-medium">Manager Workspace</span>
                  </div>
                  <ArrowRight className="w-3 h-3 text-muted-foreground" />
                </Link>
                <Link href="/executive" className="flex items-center justify-between p-2 rounded-md hover:bg-muted border border-transparent hover:border-border transition-all">
                  <div className="flex items-center gap-2">
                    <LineChart className="w-4 h-4 text-purple-500" />
                    <span className="text-sm font-medium">Executive Workspace</span>
                  </div>
                  <ArrowRight className="w-3 h-3 text-muted-foreground" />
                </Link>
              </div>
            </CardContent>
          </Card>

        </div>
      </div>
      </div>
    </div>
  )
}

function FlowStep({ agent, icon: Icon, color, status, consumed, output }: { agent: string, icon: any, color: string, status: string, consumed: string, output: string }) {
  return (
    <div className="relative flex items-start gap-4 mb-8 last:mb-0">
      <div className={`absolute left-[-27px] bg-background border-2 border-border rounded-full p-1.5 ${color}`}>
        <Icon className="w-4 h-4" />
      </div>
      <div className="w-full bg-muted/20 border border-border/50 rounded-lg p-4">
        <div className="flex justify-between items-start mb-2">
          <span className={`text-sm font-bold ${color}`}>{agent}</span>
          <span className="text-xs px-2 py-0.5 rounded bg-background border border-border text-muted-foreground">{status}</span>
        </div>
        <div className="grid grid-cols-2 gap-4 mt-3">
          <div>
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold block mb-1">Data Consumed</span>
            <span className="text-xs text-foreground bg-background px-2 py-1 rounded border border-border inline-block">{consumed}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold block mb-1">Output Generated</span>
            <span className="text-xs text-foreground bg-background px-2 py-1 rounded border border-border inline-block">{output}</span>
          </div>
        </div>
      </div>
    </div>
  )
}

function SparklesIcon(props: any) {
  return <Zap {...props} /> // Fallback using zap
}
