/**
 * Represents the role of the user accessing the dashboard.
 */
export type UserRole = "sales_rep" | "manager";

/**
 * Health trend indicator for overall pipeline or individual deals.
 */
export type HealthTrend = "improving" | "stable" | "declining";

/**
 * Risk level for deals or opportunities.
 */
export type RiskLevel = "low" | "medium" | "high";

/**
 * Priority levels for tasks and actions.
 */
export type PriorityLevel = "critical" | "high" | "medium";

/**
 * Represents a single deal in the sales pipeline.
 */
export interface MyDeal {
  id: string;
  company: string;
  stage: string;
  value: number;
  confidence: number;
  healthScore: number;
  riskLevel: RiskLevel;
  lastActivity: string;
}

/**
 * Represents a task assigned to a sales representative.
 */
export interface MyTask {
  priority: PriorityLevel;
  task: string;
  relatedDeal?: string;
  clientId?: string;
  dueDate: string;
}

/**
 * Represents a risk identified in the sales pipeline.
 */
export interface MyRisk {
  company: string;
  riskScore: number;
  riskLevel: RiskLevel;
  riskFactors: string[];
  recommendedActions: string[];
}

/**
 * Executive summary data for the sales representative view.
 */
export interface ExecutiveSummary {
  totalDeals: number;
  healthyDeals: number;
  watchDeals: number;
  atRiskDeals: number;
  pipelineHealthScore: number;
  expectedRevenue: number;
  avgConfidence: number;
  healthTrend: HealthTrend;
  executiveSummaryText?: string;
  usedCachedData?: boolean;
}

export interface RepPerformance {
  userId: string;
  name: string;
  score: number;
}

/**
 * Summary data for a manager overseeing a team.
 */
export interface TeamSummary {
  activeDeals: number;
  healthyDeals: number;
  watchDeals: number;
  atRiskDeals: number;
  avgPipelineHealth: number;
  avgConfidence: number;
  topPerformer: RepPerformance;
  needsAttention: RepPerformance;
  teamSummaryText?: string;
  usedCachedData?: boolean;
}

/**
 * Represents a specific pattern insight identified by the learning engine.
 */
export interface PatternInsight {
  id: string;
  objectionType: string;
  pattern: string;
  effectivenessScore: number;
  wins: number;
  losses: number;
  uses: number;
  lastUpdated: string;
}

/**
 * Represents an objection insight and how to handle it.
 */
export interface ObjectionInsight {
  objectionType: string;
  count: number;
  percentage: number;
}

/**
 * Insights and patterns generated by the Learning Intelligence engine.
 */
export interface LearningIntelligence {
  topPatterns: PatternInsight[];
  weakestPatterns: PatternInsight[];
  topObjections: ObjectionInsight[];
  fastestGrowingPatterns: PatternInsight[];
  learningSummaryText?: string;
  usedCachedData?: boolean;
}

/**
 * Represents an action item for a manager to take.
 */
export interface ManagerAction {
  priority: PriorityLevel;
  action: string;
  reason: string;
  relatedDeal?: string;
}

export interface ActionCenterData {
  actions: ManagerAction[];
  actionSummaryText?: string;
  usedCachedData?: boolean;
}

import { CoachingReport } from "../coaching/types";

export interface TopPerformer {
  repId: string;
  name: string;
  performanceScore: number;
  strengths: string[];
}

export interface CoachingCandidate {
  repId: string;
  name: string;
  performanceScore: number;
  weaknesses: string[];
  recommendedSkills: string[];
}

export interface AggregatedSkillGap {
  skill: string;
  frequency: number;
  severity: "low" | "medium" | "high";
  affectedReps: string[];
}

export interface RepCoachingSummary {
  topPerformers: TopPerformer[];
  coachingCandidates: CoachingCandidate[];
  criticalSkillGaps: AggregatedSkillGap[];
  coachingReports: CoachingReport[];
  coachingSummaryText?: string;
  usedCachedData?: boolean;
}

/**
 * Unified Dashboard Data structure supporting both Sales Reps and Managers.
 * Manager view will include the optional fields.
 */
export interface DashboardData {
  role: UserRole;
  executiveSummary: ExecutiveSummary;
  myDeals: MyDeal[];
  myTasks: MyTask[];
  myRisks: MyRisk[];
  teamSummary?: TeamSummary;
  learningIntelligence?: LearningIntelligence;
  actionCenter?: ActionCenterData;
  coachingSummary?: RepCoachingSummary;
}
