/**
 * Represents the role of the user accessing the dashboard.
 */
export type UserRole = "sales_rep" | "manager";

/**
 * Health trend indicator for overall pipeline or individual deals.
 */
export type HealthTrend = "improving" | "stable" | "declining";

/**
 * Risk level for deals or opportunities.
 */
export type RiskLevel = "low" | "medium" | "high";

/**
 * Priority levels for tasks and actions.
 */
export type PriorityLevel = "critical" | "high" | "medium";

/**
 * Represents a single deal in the sales pipeline.
 */
export interface MyDeal {
  id: string;
  company: string;
  stage: string;
  value: number;
  confidence: number;
  healthScore: number;
  riskLevel: RiskLevel;
  lastActivity: string;
}

/**
 * Represents a task assigned to a sales representative.
 */
export interface MyTask {
  priority: PriorityLevel;
  task: string;
  relatedDeal?: string;
  dueDate: string;
}

/**
 * Represents a risk identified in the sales pipeline.
 */
export interface MyRisk {
  company: string;
  riskScore: number;
  riskLevel: RiskLevel;
  riskFactors: string[];
  recommendedActions: string[];
}

/**
 * Executive summary data for the sales representative view.
 */
export interface ExecutiveSummary {
  totalDeals: number;
  healthyDeals: number;
  watchDeals: number;
  atRiskDeals: number;
  pipelineHealthScore: number;
  expectedRevenue: number;
  avgConfidence: number;
  healthTrend: HealthTrend;
}

/**
 * Summary data for a manager overseeing a team.
 */
export interface TeamSummary {
  activeDeals: number;
  healthyDeals: number;
  watchDeals: number;
  atRiskDeals: number;
  avgPipelineHealth: number;
  avgConfidence: number;
  topPerformer: string;
  needsAttention: string[];
}

/**
 * Represents a specific pattern insight identified by the learning engine.
 */
export interface PatternInsight {
  pattern: string;
  impactScore: number;
  description: string;
}

/**
 * Represents an objection insight and how to handle it.
 */
export interface ObjectionInsight {
  objection: string;
  frequency: number;
  suggestedResponse: string;
}

/**
 * Insights and patterns generated by the Learning Intelligence engine.
 */
export interface LearningIntelligence {
  topPatterns: PatternInsight[];
  weakestPatterns: PatternInsight[];
  topObjections: ObjectionInsight[];
  fastestGrowingPatterns: PatternInsight[];
}

/**
 * Represents an action item for a manager to take.
 */
export interface ManagerAction {
  priority: PriorityLevel;
  action: string;
  reason: string;
  relatedDeal?: string;
}

/**
 * Unified Dashboard Data structure supporting both Sales Reps and Managers.
 * Manager view will include the optional fields.
 */
export interface DashboardData {
  role: UserRole;
  executiveSummary: ExecutiveSummary;
  myDeals: MyDeal[];
  myTasks: MyTask[];
  myRisks: MyRisk[];
  teamSummary?: TeamSummary;
  learningIntelligence?: LearningIntelligence;
  actionCenter?: ManagerAction[];
}
