import { DealStrength, DealWeakness, DealBlocker } from "./types";

interface HealthInput {
    score: number;
}

interface RiskInput {
    riskLevel: string;
}

interface StrategyAnalysis {
    strengths: DealStrength[];
    weaknesses: DealWeakness[];
    blockers: DealBlocker[];
}

/**
 * Deterministically generates actionable next steps for sales representatives.
 * Maps identified blockers and weaknesses to explicitly defined sales skills.
 */
export function generateNextActions(
    health: HealthInput,
    risk: RiskInput,
    analysis: StrategyAnalysis
): { nextActions: string[], recommendedSkills: string[] } {
    
    // Track actions along with a deterministic priority score
    const actions: { action: string, skill?: string, score: number }[] = [];

    // Helper to evaluate keyword triggers within descriptions
    const matches = (text: string, keywords: string[]) => {
        const lower = text.toLowerCase();
        return keywords.some(kw => lower.includes(kw));
    };

    // 1. Analyze Blockers (Highest Impact: 80-100)
    for (const blocker of analysis.blockers) {
        if (blocker.type === "commercial" || matches(blocker.description, ["price", "cost", "budget", "expensive"])) {
            actions.push({ action: "Address pricing concerns", skill: "pricing-objection", score: 100 });
        } else if (blocker.type === "legal" || matches(blocker.description, ["procurement", "contract", "security"])) {
            actions.push({ action: "Map procurement process", skill: "enterprise-procurement", score: 95 });
        } else if (blocker.type === "relationship" || matches(blocker.description, ["stakeholder", "champion", "decision maker", "ghosted"])) {
            actions.push({ action: "Escalate executive sponsor", skill: "stakeholder-mapping", score: 90 });
        } else if (matches(blocker.description, ["roi", "value", "business case"])) {
            actions.push({ action: "Run ROI workshop", skill: "roi-conversations", score: 85 });
        } else if (matches(blocker.description, ["discount", "terms", "margin"])) {
            actions.push({ action: "Review trade-offs to protect margin", skill: "negotiation", score: 82 });
        } else {
            // Generic blocker action
            actions.push({ action: `Resolve ${blocker.type} blocker: ${blocker.description}`, score: 80 });
        }
    }

    // 2. Analyze Weaknesses (Medium Impact: 65-75)
    for (const weakness of analysis.weaknesses) {
        if (matches(weakness.description, ["health"])) {
            actions.push({ action: "Re-qualify deal criteria to improve pipeline health", skill: "qualification", score: 75 });
        } else if (matches(weakness.description, ["velocity", "stalled"])) {
            actions.push({ action: "Inject compelling event to increase deal velocity", skill: "proposal", score: 70 });
        } else if (matches(weakness.description, ["confidence"])) {
            actions.push({ action: "Schedule internal deal review to address rep confidence", score: 65 });
        }
    }

    // 3. Baseline Triggers from Risk and Health (Lower Impact: 55-60)
    if (risk.riskLevel === "high") {
        actions.push({ action: "Execute formal risk mitigation plan", score: 60 });
    }
    
    if (health.score < 50) {
        actions.push({ action: "Perform deep discovery to uncover new pain points", skill: "discovery-calls", score: 55 });
    }

    // Sort by priority score (descending)
    actions.sort((a, b) => b.score - a.score);

    // Deduplicate actions to ensure clean output
    const uniqueActions = new Map<string, { action: string, skill?: string }>();
    for (const act of actions) {
        if (!uniqueActions.has(act.action)) {
            uniqueActions.set(act.action, act);
        }
    }

    // Strictly enforce the 5-action limit
    const finalActions = Array.from(uniqueActions.values()).slice(0, 5);
    
    // Extract unique recommended skills generated by the mapped actions
    const skillsSet = new Set<string>();
    for (const act of finalActions) {
        if (act.skill) {
            skillsSet.add(act.skill);
        }
    }

    return {
        nextActions: finalActions.map(a => a.action),
        recommendedSkills: Array.from(skillsSet)
    };
}
